### ISSUE TITLE
Fix FRED2 dependency issue regarding SVMlight

### ISSUE THREAD

**Issue by christopher-mohr** [nf-core/epitopeprediction#1]
@apeltzer I guess we have to build a recipe for SVMlight and rebuild FRED2 package

**Comment by apeltzer** [comment]
Which is it? 

http://svmlight.joachims.org/

https://bitbucket.org/wcauchois/pysvmlight 

?

**Comment by apeltzer** [comment]
Which is it? 

http://svmlight.joachims.org/

https://bitbucket.org/wcauchois/pysvmlight 

?

**Comment by christopher-mohr** [comment]
Should be this one: https://pypi.org/project/svmlight/

**Comment by apeltzer** [comment]
Which means we need to package the main svmlight library as well!

**Comment by christopher-mohr** [comment]
@apeltzer you did this right? (https://bioconda.github.io/recipes/svmlight/README.html#package-svmlight) I guess we can close this issue...

**Comment by apeltzer** [comment]
Yes, this should be fine.
