### ISSUE TITLE
Implementation of the sample sheet in the pipeline

### ISSUE THREAD

**Issue by marissaDubbelaar** [nf-core/epitopeprediction#102]
It could be suggested that we create the following annotation for the input file:

* sample ID, 
* vcf file
* alleles (A*01:01), 
* peptide sequences file*,
* protein file

- The question here is where fo the id and sequence stand for (UniProt id and peptide sequence). Would it not be interesting to include the associated protein here as well?

**Comment by marissaDubbelaar** [comment]
@jonasscheid, @christopher-mohr 
I noticed that the check_requested_models.py doesn't take "A*01:01;A*02:01" as input but "HLA-A*01:01;HLA-A*02:01". 
So we need to update this in the check_samplesheet.py that it checks whether the HLA types start with "H-2-", or "HLA-"

**Comment by jonasscheid** [comment]
How about leaving the mouse nomenclature as is and allow 2 notations for the HLA alleles: With and without "HLA-" prefix.
I noticed that I need to allow mouse alleles in the check_samplesheet.py as well so I need to update it anyway. Lets wait on @christopher-mohr 's suggestion

**Comment by ggabernet** [comment]
Done in #124
