### ISSUE TITLE
Neoepitopeprediction is too memory demanding

### ISSUE THREAD

**Issue by jonasscheid** [nf-core/epitopeprediction#140]
### Description of feature

The splitting of `vcf` files is currently done chromosome-wise. However, `vcf` files can contain a skewed distribution of variants over the genome, meaning one chromosome can report a remarkable number of variants while another chromosome almost has none. Processing large numbers of variants chromosome-wise therefore leads to an inefficient use of memory and can crash the pipeline.

I would propose to alter the `snpsift_split` [module](https://github.com/nf-core/epitopeprediction/blob/1afbbf19ed6adca477451a3c42e2e0ac0c75af28/modules/local/snpsift_split.nf#L18) with the addition `SnpSift split -l {number of variants}` to split the `vcf` file with a fixed number of variants (e.g. 50 or 100)

**Comment by christopher-mohr** [comment]
Hi @jonasscheid, thanks for the suggestion. As we discussed earlier this would definitely make sense in certain scenarios. However, I would definitely want to keep both options at that point. 

I have to think about this a bit more but I think there could be (rare) cases where splitting by the number of variants might alter the results when you have multiple variants that fall on the same transcript.
