### ISSUE TITLE
Missing output information in neoepitopeprediction snvs and indels

### ISSUE THREAD

**Issue by jonasscheid** [nf-core/epitopeprediction#141]
### Description of the bug

Including two vcf files, one containing SNVs and one containing small indels, reduces the output information of SNVs. E.g.
Run with SNV only (header):
`sequence	length	chr	pos	gene	transcripts	proteins	variant type	method	DP	HLA-A*01:01 affinity	HLA-A*01:01 binder	HLA-A*01:01 score	HLA-A*02:01 affinity	HLA-A*02:01 binder	HLA-A*02:01 score	HLA-B*18:01 affinity	HLA-B*18:01 binder	HLA-B*18:01 score	HLA-B*27:05 affinity	HLA-B*27:05 binder	HLA-B*27:05 score	MQ	MQ0	NORMAL.AU	NORMAL.CU	NORMAL.DP	NORMAL.FDP	NORMAL.GU	NORMAL.SDP	NORMAL.SUBDP	NORMAL.TU	NT	QSS	QSS_NT	ReadPosRankSum	SGT	SNVSB	SOMATIC	SomaticEVS	TQSS	TQSS_NT	TUMOR.AU	TUMOR.CU	TUMOR.DP	TUMOR.FDP	TUMOR.GU	TUMOR.SDP	TUMOR.SUBDP	TUMOR.TU	homozygous	synonymous	vardbid	variant details (genomic)	variant details (protein)`

Run with indel only (header):
`sequence	length	chr	pos	gene	transcripts	proteins	variant type	method`

Run with SNV and indel file (header):
`sequence	length	chr	pos	gene	transcripts	proteins	variant type	method`

**Comment by christopher-mohr** [comment]
Could not reproduce it so far. Waiting for feedback.

**Comment by jonasscheid** [comment]
Not reproducible. There might be a manual error in preprocessing steps.
Closing
