### ISSUE TITLE
Provide information about supported models

### ISSUE THREAD

**Issue by skrakau** [nf-core/epitopeprediction#21]
It would be helpful to provide information about supported models by different tools and to throw an exception or warning if a not supported peptide length or allele is specified.

**Comment by christopher-mohr** [comment]
Should be possible using the properties `supportedLength`and `supportedAlleles`of the respective prediction method class in FRED2.

**Comment by skrakau** [comment]
Addressed in https://github.com/nf-core/epitopeprediction/pull/44
