### ISSUE TITLE
show_supported_models module not called correctly

### ISSUE THREAD

**Issue by jonasscheid** [nf-core/epitopeprediction#224]
### Description of the bug

The `--show_supported_models` param [here](https://github.com/nf-core/epitopeprediction/blob/b0f0d7a5b3cd352e548901e4cc19937c73add465/workflows/epitopeprediction.nf#L173) is not working since [the modules have been renamed](https://github.com/nf-core/epitopeprediction/commit/8c0d32587c01a45fe1247477a0821db68b4148a8)
That is a quick fix, but can we move the information of supported tools into the docs?
I guess the user would expect that information there rather than via a CLI argument.

### Command used and terminal output

```console
nextflow run nf-core/epitopeprediction -profile test_peptides,docker --show_supported_models -r 2.2.1 --outdir results/show_sup_models_test
```

**Comment by thomas-davis** [comment]
Happy to take this 👍
