### ISSUE TITLE
Add splitting for peptides

### ISSUE THREAD

**Issue by skrakau** [nf-core/epitopeprediction#28]
Add splitting for peptides in process 'splitPeptides'. Currently missing, only done for variants.

**Comment by christopher-mohr** [comment]
See process ```splitVariants``` where it is already done for variants in TSV format. I guess we can just copy it for the peptide splitting.

**Comment by skrakau** [comment]
`csvtk split` splits files based on column values, e.g. based on chromosome names within `splitVariants`. For peptides that is not exactly what we would want I guess, at least it is not applicable in my case. I will make a PR tomorrow or so, just need to test it again (after I recovered my missing scripts and data).

**Comment by christopher-mohr** [comment]
> `csvtk split` splits files based on column values, e.g. based on chromosome names within `splitVariants`. For peptides that is not exactly what we would want I guess, at least it is not applicable in my case. I will make a PR tomorrow or so, just need to test it again (after I recovered my missing scripts and data).

You're right. I guess then we can just use Unix ```split```?

**Comment by apeltzer** [comment]
The call might be different then but couldn't you modify the command in a way to make this work with `csvtk` to keep further dependencies low? 

Could do a regex based approach or how does this format look like that you want to split?

**Comment by christopher-mohr** [comment]
```csvtk``` can split a file based on column values which makes sense for ```splitvariants``` because we can just split on chromosomes and get one file for each chromosome. This wouldn't make sense for peptide input since we only require the sequence and some identifier to be present which will be unique in most of the cases.

But we wouldn't need an additional dependency for ```split``` right?

**Comment by skrakau** [comment]
I used `split`, assuming that it would be available for all systems and be robust. Do you have any contradicting information?

**Comment by apeltzer** [comment]
I think I read something about some of the core utils behaving differently on different operating systems - shouldn’t matter in the container but within e.g. the conda env it might make a difference e.g. on OSX or Linux. „ps“ is one example, but also things like grep are slightly different, so split could be another false friend. 

Up to you, only wanted to ask whether there is no way around it & suggest being careful there :-)

**Comment by skrakau** [comment]
OK thanks, good to know!

**Comment by apeltzer** [comment]
Would be cool to hear if there are indeed problems if you intend to push for `split`!

**Comment by skrakau** [comment]
solved in https://github.com/nf-core/epitopeprediction/pull/29, implemented in python in the end.
