### ISSUE TITLE
Missing `fromPath` parameter

### ISSUE THREAD

**Issue by prakakrishna** [nf-core/epitopeprediction#4]
I am getting Missing `fromPath` parameter when running "nextflow run nf-core/epitopeprediction --reads '*_R{1,2}.fastq.gz' -profile standard,docker". I tried "nextflow run nf-core/epitopeprediction --reads '*_R{1,2}.fastq.gz' -profile standard,docker --fromPath ." too. Same error.

**Comment by christopher-mohr** [comment]
The version in this repo is just the initial template build based on nf-core/tools. This pipeline is work in progress. There is a PR with the first **functioning** version of the epitopeprediction pipeline which will be reviewed soon I guess.

**Comment by apeltzer** [comment]
Yes, please wait a couple of days until this will be fully functional 👍

**Comment by mpozuelo-flomics** [comment]
Hi you all, I'm getting this same error running the last version of the pipeline. Have you made any changes that could affect this?
Thanks

**Comment by christopher-mohr** [comment]
Hi @mpozuelo-flomics, what kind of input data would you like to use? If you have variant data you would use `--input` and `--peptides` in case of peptide sequences. Could you share the command you used?
