### ISSUE TITLE
Provide option to customize binder threshold

### ISSUE THREAD

**Issue by jonasscheid** [nf-core/epitopeprediction#80]
Currently the affinity threshold for a peptide prediction is set to >= 50% to decide whether a peptide is considered as a binder or not. It would be convenient to customize the threshold for each given prediction tool.

**Comment by christopher-mohr** [comment]
Hi @jonasscheid, thanks for feature request, makes totally sense. The place where we would have to change this is here (for Syfpeithi and others): 
https://github.com/nf-core/epitopeprediction/blob/ce15e440954f8e7c83c341261b82aacc8e3535ac/bin/epaa.py#L735

In addition we will need a new pipeline parameter that can be forwarded to the Python script call here:
https://github.com/nf-core/epitopeprediction/blob/ce15e440954f8e7c83c341261b82aacc8e3535ac/main.nf#L432
