### ISSUE TITLE
proper inplementation of the current netmhc_tools_import process

### ISSUE THREAD

**Issue by marissaDubbelaar** [nf-core/epitopeprediction#99]
We need to play around with this, (1) we can create a similar approach with the process and use the checksum to retrieve the netmhc* version, and (2) define this during an input check

**Comment by ggabernet** [comment]
Mostly done, but the tools that were removed will need to be re-added after Epytope release

**Comment by jonasscheid** [comment]
During the DSL2 conversion, a few functionalities for setting up netmhc were lost [here](https://github.com/nf-core/epitopeprediction/blob/a188cdcd405120a3d572110f53cca8e160bdab13/main.nf#L368). Also `gawk` and `tcsh` are missing in the container of the `PEPTIDE_PREDICTION` process to run netmhc properly

**Comment by christopher-mohr** [comment]
> During the DSL2 conversion, a few functionalities for setting up netmhc were lost [here](https://github.com/nf-core/epitopeprediction/blob/a188cdcd405120a3d572110f53cca8e160bdab13/main.nf#L368). Also `gawk` and `tcsh` are missing in the container of the `PEPTIDE_PREDICTION` process to run netmhc properly

Just as an addition and for documentation, [this](https://github.com/nf-core/epitopeprediction/blob/a188cdcd405120a3d572110f53cca8e160bdab13/main.nf#L575) is the missing part in the current `peptide prediction` process.
